import type { ItemTemplate } from './types.js';

export const ITEMS: Record<string, ItemTemplate> = {
  rusty_sword: {
    id: 'rusty_sword',
    name: 'Rusty Sword',
    description: 'A battered blade, still sharp enough to draw blood.',
    type: 'weapon',
    slot: 'weapon',
    attack: 5,
    value: 10,
  },
  iron_sword: {
    id: 'iron_sword',
    name: 'Iron Sword',
    description: 'A well-forged iron blade with a leather-wrapped hilt.',
    type: 'weapon',
    slot: 'weapon',
    attack: 12,
    value: 50,
  },
  leather_armor: {
    id: 'leather_armor',
    name: 'Leather Armor',
    description: 'Sturdy boiled leather, worn but serviceable.',
    type: 'armor',
    slot: 'armor',
    defense: 4,
    value: 30,
  },
  chainmail: {
    id: 'chainmail',
    name: 'Chainmail',
    description: 'Interlocking steel rings that turn aside most blows.',
    type: 'armor',
    slot: 'armor',
    defense: 10,
    value: 120,
  },
  health_potion: {
    id: 'health_potion',
    name: 'Health Potion',
    description: 'A crimson vial that restores vitality when consumed.',
    type: 'consumable',
    heal: 40,
    value: 15,
  },
  mana_potion: {
    id: 'mana_potion',
    name: 'Mana Potion',
    description: 'A shimmering blue elixir that restores magical energy.',
    type: 'consumable',
    heal: 0,
    value: 15,
  },
  goblin_ear: {
    id: 'goblin_ear',
    name: 'Goblin Ear',
    description: 'A grisly trophy, proof of a goblin slain.',
    type: 'quest',
    value: 0,
  },
  wolf_pelt: {
    id: 'wolf_pelt',
    name: 'Wolf Pelt',
    description: 'Thick grey fur, still warm to the touch.',
    type: 'quest',
    value: 5,
  },
  ancient_key: {
    id: 'ancient_key',
    name: 'Ancient Key',
    description: 'An ornate key covered in verdigris. It hums faintly.',
    type: 'quest',
    value: 0,
  },
  gold_coin: {
    id: 'gold_coin',
    name: 'Gold Coin',
    description: 'A gleaming coin stamped with the crest of Eldermoor.',
    type: 'misc',
    value: 1,
  },
};