import type { ItemTemplate } from './types.js';

export const ITEMS: Record<string, ItemTemplate> = {
  rusty_sword: {
    id: 'rusty_sword',
    name: 'Rusty Sword',
    description: 'A battered blade, still sharp enough to draw blood.',
    type: 'weapon',
    slot: 'weapon',
    attack: 5,
    value: 10,
    rarity: 'common',
  },
  iron_sword: {
    id: 'iron_sword',
    name: 'Iron Sword',
    description: 'A well-forged iron blade with a leather-wrapped hilt.',
    type: 'weapon',
    slot: 'weapon',
    attack: 12,
    value: 50,
    rarity: 'uncommon',
  },
  shadow_dagger: {
    id: 'shadow_dagger',
    name: 'Shadow Dagger',
    description: 'A blade that drinks the light, favored by assassins.',
    type: 'weapon',
    slot: 'weapon',
    attack: 18,
    value: 150,
    rarity: 'rare',
  },
  leather_armor: {
    id: 'leather_armor',
    name: 'Leather Armor',
    description: 'Sturdy boiled leather, worn but serviceable.',
    type: 'armor',
    slot: 'armor',
    defense: 4,
    value: 30,
    rarity: 'common',
  },
  chainmail: {
    id: 'chainmail',
    name: 'Chainmail',
    description: 'Interlocking steel rings that turn aside most blows.',
    type: 'armor',
    slot: 'armor',
    defense: 10,
    value: 120,
    rarity: 'uncommon',
  },
  plate_of_the_lich: {
    id: 'plate_of_the_lich',
    name: 'Plate of the Lich',
    description: 'Dark plate humming with necromantic wards.',
    type: 'armor',
    slot: 'armor',
    defense: 18,
    value: 400,
    rarity: 'epic',
  },
  health_potion: {
    id: 'health_potion',
    name: 'Health Potion',
    description: 'A crimson vial that restores vitality when consumed.',
    type: 'consumable',
    heal: 40,
    value: 15,
    rarity: 'common',
  },
  mana_potion: {
    id: 'mana_potion',
    name: 'Mana Potion',
    description: 'A shimmering blue elixir that restores magical energy.',
    type: 'consumable',
    heal: 0,
    value: 15,
    rarity: 'common',
  },
  goblin_ear: {
    id: 'goblin_ear',
    name: 'Goblin Ear',
    description: 'A grisly trophy, proof of a goblin slain.',
    type: 'quest',
    value: 0,
    rarity: 'common',
  },
  wolf_pelt: {
    id: 'wolf_pelt',
    name: 'Wolf Pelt',
    description: 'Thick grey fur, still warm to the touch.',
    type: 'quest',
    value: 5,
    rarity: 'common',
  },
  ancient_key: {
    id: 'ancient_key',
    name: 'Ancient Key',
    description: 'An ornate key covered in verdigris. It hums faintly.',
    type: 'quest',
    value: 0,
    rarity: 'rare',
  },
  gold_coin: {
    id: 'gold_coin',
    name: 'Gold Coin',
    description: 'A gleaming coin stamped with the crest of Eldermoor.',
    type: 'misc',
    value: 1,
    rarity: 'common',
  },
};

export function formatItemName(itemId: string): string {
  const item = ITEMS[itemId];
  if (!item) return itemId;
  const tag = item.rarity && item.rarity !== 'common' ? `[${item.rarity}] ` : '';
  return `${tag}${item.name}`;
}